name: Mirror Release From Suyu Official

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
   inputs:
      android:
        description: 'Whether to trigger an Android build (true/false/auto)'
        required: false
        default: 'true'

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    permissions: write-all

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Release Info
      id: info
      run: |
        response=$(curl -s "https://git.suyu.dev/api/v1/repos/suyu/suyu/releases")
        name=$(echo "$response" | jq -r '.[0].name')
        tag=$(echo "$response" | jq -r '.[0].tag_name')
        description=$(echo "$response" | jq -r '.[0].body')
        links=$(echo "$response" | jq -r '.[0].assets[]? | select(has("browser_download_url") and has("name")) | "- [\(.name)](\(.browser_download_url))"')

        echo "::set-output name=name::$name"
        echo "::set-output name=tag::$name"

        echo "## Changelog" > description.txt
        echo "${description}" >> description.txt
        echo "## Downloads" >> description.txt
        echo "${links}" >> description.txt
        echo "## Not Support Android 10" >>description.txt

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        makeLatest: true
        skipIfReleaseExists: true
        replacesArtifacts: true
        tag: ${{ steps.info.outputs.tag }}
        name: ${{ steps.info.outputs.name }}
        bodyFile: "description.txt"
        
