name: Mirror Early Release Gitlab From Suyu Official

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
   inputs:
      android:
        description: 'Whether to trigger an Android build (true/false/auto)'
        required: false
        default: 'true'

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    permissions: write-all

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Release Info
      id: info
      run: |
        response=$(curl -s "https://gitlab.com/suyu-emu/suyu-releases/-/tree/master")
        name=$(echo "$response" | jq -r '.[0].name')
        links=$(echo "$response" | jq -r '.[0].assets.links[]? | select(has("url") and has("name")) | "- [\(.name)](\(.url))"')
        echo "::set-output name=name::$name"
        echo "## Downloads" >> description.txt
        echo "${links}" >> description.txt
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        makeLatest: true
        skipIfReleaseExists: true
        prerelease: true
        updateOnlyUnreleased: true
        omitName: true
        omitNameDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        name: ${{ steps.info.outputs.name }}
        bodyFile: "description.txt"
